adding SV reference design for interface
pulp-platform/riscv-extension-interface pull request #108
Opened 2023-12-06 08:45 UTC by davideschiavone

1. AFAIK, parameters in packages cannot change --> move to interface?
2. Interfaces of interfaces? A main core_v_xif interface which has inside all the sub-interfaces?

2023-12-06 09:16 UTC, Gchauvon commented
Should we also add structures on top of the ones you defined to hold the handshake signals (valid/ready) ?

2023-12-06 09:24 UTC, Gchauvon commented
A way to manage parameters in packages : 

https://github.com/openhwgroup/cva6/blob/master/core/include/config_pkg.sv
https://github.com/openhwgroup/cva6/blob/master/core/include/cv32a6_embedded_config_pkg.sv

2023-12-06 14:19 UTC, christian-herber-nxp commented on src/core_v_xif_pkg.sv
> +// Copyright 2021 ETH Zurich and University of Bologna.
Copyright 2023 OpenHW Group

2023-12-06 14:20 UTC, christian-herber-nxp commented on src/core_v_xif_pkg.sv
> +// Copyright and related rights are licensed under the Solderpad Hardware
Better to replace with SPDX identifier

2024-01-10 13:30 UTC, christian-herber-nxp commented
@davideschiavone : when will there be the next heatbeat on this PR?

2024-01-10 13:56 UTC, davideschiavone commented
> @davideschiavone : when will there be the next heatbeat on this PR?

hi @christian-herber-nxp - I had more into the stack with upcoming deadlines and trips to deal with but should be on it again before or immediatly after the Tristan Rearsal

2024-01-17 13:44 UTC, christian-herber-nxp commented on src/core_v_xif_pkg.sv
> +// Copyright 2024 OpenHW Group
You cannot just remove the ETHZ and UniBo copyright. Should be 
Copyright 2021 ETH Zurich and University of Bologna
Copyright 2023-2024 OpenHW Group

2024-01-17 14:05 UTC, christian-herber-nxp commented on src/core_v_xif.sv
> +  parameter int unsigned MXLEN                  = 32
where does this come from?

2024-01-17 14:10 UTC, davideschiavone commented on src/core_v_xif.sv
> +  parameter int unsigned MXLEN                  = 32
sorry - forgot to remove it

2024-01-17 14:11 UTC, michael-platzer reviewed
> @michael-platzer, @moimfeld I added your names in the contributions as I got inspired/copied by your SV files - is that ok?

Sure, that is fine :slightly_smiling_face: although I suggest using my private mail address instead, as I do no longer have access to my TU Wien mail address.

2024-01-17 14:11 UTC, michael-platzer commented on src/core_v_xif.sv
> +// Contributor: Michael Platzer - <michael.platzer@tuwien.ac.at>
```suggestion
// Contributor: Michael Platzer <michael.platzer@hotmail.com>
```

2024-01-17 14:17 UTC, christian-herber-nxp commented on src/core_v_xif_pkg.sv
> +// Copyright 2024 OpenHW Group
if you wrote them from scratch, yes. If you copy pastad stuff, then their copyright is valid.

2024-01-17 14:19 UTC, davideschiavone commented on src/core_v_xif_pkg.sv
> +// Copyright 2024 OpenHW Group
then I will add it back

2024-01-17 14:21 UTC, christian-herber-nxp commented on src/core_v_xif.sv
> +// Solderpad Hardware License, Version 2.1, see LICENSE.md for details.
There is no LICENSE.MD

2024-01-17 14:22 UTC, davideschiavone commented on src/core_v_xif_pkg.sv
> +// Copyright 2024 OpenHW Group
I added also the TU Wien copyright as I copied from there as well

2024-01-17 14:23 UTC, christian-herber-nxp commented on src/core_v_xif.sv
> +// Solderpad Hardware License, Version 2.1, see LICENSE.md for details.
btw. the specification uses Solderpad 0.51.
I checked in the meeting today if we should upgrade to a newer one.
For the specification itself, this would anyway default to Apache 2.0 I guess.
I do not know if upgrading to a newer solder pad license would require the consent of all contributors (I would assume yes, but the number of contributors is also fairly low)

2024-01-17 14:25 UTC, davideschiavone commented on src/core_v_xif.sv
> +// Solderpad Hardware License, Version 2.1, see LICENSE.md for details.
Let me add it

2024-01-17 14:25 UTC, davideschiavone commented on src/core_v_xif.sv
> +// Solderpad Hardware License, Version 2.1, see LICENSE.md for details.
I added LICENSE.md on Solderpad 2.1 - does it make any difference?

2024-01-17 14:30 UTC, christian-herber-nxp commented on src/core_v_xif.sv
> +// Solderpad Hardware License, Version 2.1, see LICENSE.md for details.
the original authors (actually all authors) have contributed under the assumption that this is licensed under solderpad 0.51. You cannot simply decide to change the license, at least i would be quite sure of that. Even if it is just an upgrade to a newer version.

2024-01-17 14:31 UTC, christian-herber-nxp commented on src/core_v_xif.sv
> +// Solderpad Hardware License, Version 2.1, see LICENSE.md for details.
I should I don't think there is a practical problem, but i would say there is a legal one. If you would create a PR to change the license, and have all contributors approve it, then this should the safest way to do it

2024-01-17 15:05 UTC, moimfeld commented
> @michael-platzer, @moimfeld I added your names in the contributions as I got inspired/copied by your SV files - is that ok?

Yes, that's great 😃  Thanks @davideschiavone!

2024-01-17 15:06 UTC, moimfeld approved these changes

2024-01-23 16:09 UTC, christian-herber-nxp commented
I just had a look at the license and header situation now. This is looking complicated. There are now different licenses, but it is not clear what part of the file falls under which license. Maybe its something to discuss tomorrow, but i would hope to get everything under a single license. Otherwise it is not practical

2024-01-24 08:13 UTC, davideschiavone commented
> I just had a look at the license and header situation now. This is looking complicated. There are now different licenses, but it is not clear what part of the file falls under which license. Maybe its something to discuss tomorrow, but i would hope to get everything under a single license. Otherwise it is not practical

Can you please point me to the files? It seems they are all 0.51 Solderpad

2024-01-24 08:22 UTC, christian-herber-nxp commented
> > I just had a look at the license and header situation now. This is looking complicated. There are now different licenses, but it is not clear what part of the file falls under which license. Maybe its something to discuss tomorrow, but i would hope to get everything under a single license. Otherwise it is not practical
> 
> Can you please point me to the files? It seems they are all 0.51 Solderpad

the .sv file had three separate headers in the file, some with 2.1 and some with 0.51

2024-01-24 08:48 UTC, davideschiavone commented
> > > I just had a look at the license and header situation now. This is looking complicated. There are now different licenses, but it is not clear what part of the file falls under which license. Maybe its something to discuss tomorrow, but i would hope to get everything under a single license. Otherwise it is not practical
> > 
> > 
> > Can you please point me to the files? It seems they are all 0.51 Solderpad
> 
> the .sv file had three separate headers in the file, some with 2.1 and some with 0.51

true - @DBees , how do we address this issue?

2024-01-24 09:28 UTC, davideschiavone commented
- [ ] Move LICENSE.md into the `src` folder

- [ ] Change everything to SHL 2-0

2024-01-24 09:44 UTC, christian-herber-nxp requested changes
change terminology to inclusive terms

2024-01-24 20:35 UTC, mp-17 commented
> * [ ]  Move LICENSE.md into the `src` folder
> * [ ]  Change everything to SHL 2-0
> 
> @mp-17 can you check if ETH Z is ok to move to SHL 2?

Hey Davide, I asked internally; green light from us to move to Solderpad 2.0!

2024-01-26 02:13 UTC, DBees commented
@davideschiavone I believe this spec is being published by OpenHW on behalf of its members. Members have granted OpenHW a sublicensable copyright license to do so. I don't think the spec needs to list each member's license on their own particular part of the spec. Pardon me if I didn't follow the gist of the question above

2024-01-30 10:39 UTC, davideschiavone commented
hi @moimfeld , can we change the license to 2.0?

2024-01-30 10:47 UTC, christian-herber-nxp commented
I think we would want to change to 2.1?

2024-01-30 11:59 UTC, moimfeld commented
Hi @davideschiavone and @christian-herber-nxp 
Both the change to Solderpad 2.0 and Solderpad 2.1 are fine for me.

2024-02-01 15:07 UTC, merged